export const COMMUNES_PAR_WILAYA: Record<string, string[]> = {
  Adrar: [
    "Adrar",
    "Tamest",
    "Charouine",
    "Reggane",
    "Inzghmir",
    "Tit",
    "Ksar Kaddour",
    "Tsabit",
    "Timimoun",
    "Ouled Said",
    "Zaouiet Kounta",
    "Aoulef",
    "Timokten",
    "Tamantit",
    "Fenoughil",
    "Tinerkouk",
    "Deldoul",
    "Sali",
    "Akabli",
    "Metarfa",
    "Ouled Ahmed Timmi",
    "Bouda",
    "Aougrout",
    "Talmine",
    "Bordj Badji Mokhtar",
    "Sbaa",
    "Ouled Aissa",
  ],

  Chlef: [
    "Chlef",
    "Ténès",
    "Benairia",
    "El Karimia",
    "Tadjena",
    "Taougrite",
    "Beni Haoua",
    "Sobha",
    "Harchoun",
    "Ouled Fares",
    "Sidi Akkacha",
    "Boukadir",
    "Beni Rached",
    "Talassa",
    "Herenfa",
    "Oued Goussine",
    "Dahra",
    "Ouled Abbès",
    "Sendjas",
    "Zeboudja",
    "Oued Sly",
    "Abou El Hassan",
    "El Marsa",
    "Chettia",
    "Sidi Abderrahmane",
    "Moussadek",
    "El Hadjadj",
    "Labiod Medjadja",
    "Oued Fodda",
    "Ouled Ben Abdelkader",
    "Bouzghaia",
    "Aïn Merane",
    "Oum Drou",
    "Breira",
    "Beni Bouateb",
    "Beni Zentis",
  ],

  Laghouat: [
    "Laghouat",
    "Ksar El Hirane",
    "Bennasser Benchohra",
    "Sidi Makhlouf",
    "Hassi Delaa",
    "Hassi R'Mel",
    "Aïn Madhi",
    "Tadjemout",
    "Kheneg",
    "Gueltat Sidi Saâd",
    "Aïn Sidi Ali",
    "Beidha",
    "Brida",
    "El Ghicha",
    "Hadj Mechri",
    "Sebgag",
    "Taouiala",
    "Tadjrouna",
    "Aflou",
    "El Assafia",
    "Oued Morra",
    "Oued M'Zi",
    "El Houaita",
    "Sidi Bouzid",
  ],

  "Oum El Bouaghi": [
    "Oum El Bouaghi",
    "Aïn Beïda",
    "Aïn M'lila",
    "Behir Chergui",
    "El Amiria",
    "Sigus",
    "El Belala",
    "Aïn Babouche",
    "Berriche",
    "Ouled Hamla",
    "Dhala",
    "Aïn Kercha",
    "Hanchir Toumghani",
    "El Djazia",
    "Aïn Diss",
    "Fkirina",
    "Souk Naâmane",
    "Zorg",
    "El Fedjoudj Boughrara Saoudi",
    "Ouled Gacem",
    "Bir Chouhada",
    "Ksar Sbahi",
    "Oued Nini",
    "Meskiana",
    "Aïn Fekroune",
    "Rahia",
    "Aïn Zitoun",
    "Ouled Zouaï",
    "Aïn Kerma",
  ],

  Batna: [
    "Batna",
    "Ghassira",
    "Maafa",
    "Merouana",
    "Seriana",
    "Menaa",
    "El Madher",
    "Tazoult",
    "Ngaous",
    "Guigba",
    "Inoughissen",
    "Ouyoun El Assafir",
    "Djerma",
    "Bitam",
    "Abdelkader Azil",
    "Arris",
    "Kimmel",
    "Tilatou",
    "Aïn Djasser",
    "Ouled Selam",
    "Tigherghar",
    "Aïn Yagout",
    "Fesdis",
    "Sefiane",
    "Rahbat",
    "Tighanimine",
    "Lemsane",
    "Ksar Belezma",
    "Seggana",
    "Ichmoul",
    "Foum Toub",
    "Beni Foudhala El Hakania",
    "Oued El Ma",
    "Talkhamt",
    "Bouzina",
    "Chemora",
    "Oued Chaaba",
    "Taxlent",
    "Gosbat",
    "Ouled Aouf",
    "Boumagueur",
    "Barika",
    "Djezzar",
    "Tkout",
    "Aïn Touta",
    "Hidoussa",
    "Teniet El Abed",
    "Oued Taga",
    "Ouled Fadel",
    "Timgad",
    "Ras El Aioun",
    "Chir",
    "Ouled Si Slimane",
    "Zanat El Beida",
    "Mdhilla",
    "Boumia",
    "Boulhilat",
    "Lazrou",
    "Bouksir",
    "Amdoukal",
  ],

  Béjaïa: [
    "Béjaïa",
    "Amizour",
    "Ferraoun",
    "Taourirt Ighil",
    "Chelata",
    "Tamokra",
    "Timezrit",
    "Souk El Tenine",
    "Melbou",
    "Seddouk",
    "Darguina",
    "Adekar",
    "Akbou",
    "Sidi Aïch",
    "Chemini",
    "Souk Oufella",
    "Tazmalt",
    "Ighil Ali",
    "Ifenain Ilmathen",
    "Tifra",
    "Ighram",
    "Amalou",
    "Beni Ksila",
    "Ouzellaguen",
    "Bouhamza",
    "Beni Melikeche",
    "Semaoun",
    "Kendira",
    "Toudja",
    "Ait Daoud",
    "Barbacha",
    "Beni K'sila",
    "Ouled Djellal",
    "Ait R'zine",
    "Tamridjet",
    "Akfadou",
    "Leflaye",
    "Kherrata",
    "Draa El Kaid",
    "Tamdjirt",
    "Boukhelifa",
    "Tichi",
    "Sidi Ayad",
    "Aokas",
    "Beni Djellil",
    "Ait Smail",
    "Boukerdane Sebaou",
    "Tibane",
    "Tala Hamza",
    "Beni Maouche",
    "Oued Ghir",
  ],

  Biskra: [
    "Biskra",
    "Oulad Djellal",
    "Sidi Okba",
    "Sidi Khaled",
    "El Kantara",
    "Aïn Naga",
    "Zeribet El Oued",
    "El Feidh",
    "El Outaya",
    "Djemorah",
    "Tolga",
    "Lioua",
    "Lichana",
    "Ourlal",
    "M'Ziraa",
    "Foughala",
    "Bordj Ben Azzouz",
    "Bouchagroune",
    "Branis",
    "Chetma",
    "Ouled Harkat",
    "Mekhadma",
    "El Hadjab",
    "Chaïba",
    "Bou Chegroun",
    "El Ghrous",
    "El Mizaraa",
    "Sidi Mabrouk",
    "Aïn Zaatout",
    "Ras El Miad",
    "Besbes",
    "Doucen",
    "Khenguet Sidi Nadji",
  ],

  Béchar: [
    "Béchar",
    "Erg Ferradj",
    "Ouled Khoudir",
    "Meridja",
    "Timoudi",
    "Lahmar",
    "Béni Abbès",
    "Tabelbala",
    "Igli",
    "Taghit",
    "El Ouata",
    "Boukais",
    "Mogheul",
    "Abadla",
    "Kerzaz",
    "Ksabi",
    "Tamtert",
    "Beni Ikhlef",
    "Mechraa Houari Boumediene",
    "Meridja",
  ],

  Blida: [
    "Blida",
    "Chréa",
    "Boufarik",
    "Ouled Yaïch",
    "Chebli",
    "Bouinan",
    "Oued El Alleug",
    "Beni Mered",
    "Bougara",
    "Larbaâ",
    "Oued Djer",
    "Soumaa",
    "Mouzaïa",
    "Souhane",
    "Meftah",
    "Ouled Selama",
    "Bouarfa",
    "Beni Tamou",
    "Djebabra",
    "Guerrouaou",
    "Aïn Romana",
    "Hammam Melouane",
    "Ben Khellil",
    "Ouled Aïch",
    "El Affroun",
  ],

  Bouira: [
    "Bouira",
    "El Asnam",
    "Guerrouma",
    "Souk El Khemis",
    "Kadiria",
    "Hanif",
    "Dirah",
    "Aïn Bessem",
    "Bir Ghbalou",
    "Khabouzia",
    "Ahl El Ksar",
    "Bouderbala",
    "Raouraoua",
    "Taghzout",
    "Ridane",
    "Djebahia",
    "Aïn El Hadjar",
    "Haizer",
    "Lakhdaria",
    "Maala",
    "Chorfa",
    "Bechloul",
    "Bordj Okhriss",
    "El Hachimia",
    "Aomar",
    "Aïn Turk",
    "Saharidj",
    "Dechmia",
    "Ait Laaziz",
    "Taourirt",
    "Hadjera Zerga",
    "Aghbalou",
    "Aïn Laloui",
    "El Adjiba",
    "Aïn Bessem",
    "Sour El Ghozlane",
    "M'Chedallah",
    "Aïn El Turc",
    "Zbarbar",
    "Aïn Taghrout",
    "Ouled Rached",
    "Aghbalou",
    "Ahl El Ksar",
    "El Mokrani",
    "Boukram",
  ],

  Tamanrasset: [
    "Tamanrasset",
    "Abalessa",
    "In Ghar",
    "In Guezzam",
    "Tazrouk",
    "Idles",
    "Tin Zaouatine",
    "In Amguel",
    "Foggaret Ezzoua",
    "Tazoult",
    "Inamenas",
  ],

  Tébessa: [
    "Tébessa",
    "Bir El Ater",
    "Cheria",
    "Stah Guentis",
    "El Aouinet",
    "Lahouidjbet",
    "Safsaf El Ouesra",
    "Hammamet",
    "Negrine",
    "Bir Mokkadem",
    "El Kouif",
    "Morsott",
    "El Ogla",
    "Bir Dheheb",
    "El Ogla El Malha",
    "Gourigueur",
    "Bekkaria",
    "Boukhadra",
    "Ouenza",
    "El Ma Labiodh",
    "Tlidjene",
    "Aïn Zerga",
    "El Meridj",
    "Boulhaf Dyr",
    "Bedjene",
    "El Mezeraa",
    "Ferkane",
  ],

  Tlemcen: [
    "Tlemcen",
    "Beni Mester",
    "Aïn Tallout",
    "Remchi",
    "El Fehoul",
    "Sabra",
    "Ghazaouet",
    "Souani",
    "Djebala",
    "El Gor",
    "Oued Lakhdar",
    "Aïn Fezza",
    "Ouled Mimoun",
    "Amieur",
    "Aïn Youcef",
    "Zenata",
    "Beni Snous",
    "Bab El Assa",
    "Dar Yaghmouracene",
    "Fellaoucene",
    "Azails",
    "Sebbaa Chioukh",
    "Terni Beni Hediel",
    "Bensekrane",
    "Aïn Kebira",
    "Mansourah",
    "Beni Boussaid",
    "Bouhlou",
    "Sidi Abdelli",
    "Sebdou",
    "Beni Ouarsous",
    "Sidi Medjahed",
    "Béni Bahdel",
    "El Bouihi",
    "Honaine",
    "Tianet",
    "Ouled Riah",
    "Souk Tlata",
    "Aïn Nehala",
    "Hennaya",
    "Maghnia",
    "Hammam Boughrara",
    "Souahlia",
    "Msirda Fouaga",
    "Aïn Fetah",
    "El Aricha",
    "Souk El Khemis",
    "Sidi Djilali",
    "Beni Khellad",
    "Beni Semiel",
    "Marsa Ben M'hidi",
  ],

  Tiaret: [
    "Tiaret",
    "Medroussa",
    "Aïn Bouchekif",
    "Sidi Ali Mellal",
    "Aïn Zarit",
    "Aïn Deheb",
    "Sidi Bakhti",
    "Medrissa",
    "Zmalet El Emir Abdelkader",
    "Madna",
    "Sebt",
    "Mellakou",
    "Dahmouni",
    "Rahouia",
    "Mahdia",
    "Sougueur",
    "Sidi Abdelghani",
    "Aïn El Hadid",
    "Ouled Djerad",
    "Naima",
    "Meghila",
    "Guertoufa",
    "Sidi Hosni",
    "Djillali Ben Amar",
    "Sebaine",
    "Tousnina",
    "Frenda",
    "Aïn Kermes",
    "Ksar Chellala",
    "Rechaiga",
    "Nadorah",
    "Tagdemt",
    "Oued Lilli",
    "Mechraa Safa",
    "Hamadia",
    "Chehaima",
    "Takhemaret",
    "Sidi Abderrahmane",
    "Serghine",
    "Bougara",
    "Faidja",
    "Tidda",
  ],

  "Tizi Ouzou": [
    "Tizi Ouzou",
    "Aïn El Hammam",
    "Akbil",
    "Freha",
    "Souamaâ",
    "Mechtras",
    "Irdjen",
    "Timizart",
    "Makouda",
    "Draa El Mizan",
    "Tizi Gheniff",
    "Bounouh",
    "Aït Chaffaa",
    "Frikat",
    "Beni Aïssi",
    "Beni Zmenzer",
    "Iferhounene",
    "Azazga",
    "Illoula Oumalou",
    "Yakouren",
    "Larbaâ Nath Irathen",
    "Tizi Rached",
    "Zekri",
    "Ouaguenoun",
    "Aïn Zaouïa",
    "M'Kira",
    "Aït Yahia",
    "Aït Mahmoud",
    "Maatkas",
    "Aït Boumehdi",
    "Abi Youcef",
    "Beni Douala",
    "Illilten",
    "Bouzeguène",
    "Aït Aggouacha",
    "Ouadhia",
    "Azeffoun",
    "Tigzirt",
    "Aït Aïssa Mimoun",
    "Boghni",
    "Ifigha",
    "Aït Oumalou",
    "Tirmitine",
    "Akerrou",
    "Yatafen",
    "Beni Z'menzer",
    "Iflissen",
    "Boudjima",
    "Aït Yahia Moussa",
    "Souk El Tenine",
    "Aït Khelili",
    "Sidi Naamane",
    "Imsouhal",
    "Tadmaït",
    "Aït Bouaddou",
    "Assi Youcef",
    "Aït Toudert",
  ],

  Alger: [
    "Alger Centre",
    "Sidi M'Hamed",
    "El Madania",
    "Belouizdad",
    "Bab El Oued",
    "Bologhine",
    "Casbah",
    "Oued Koriche",
    "Bir Mourad Raïs",
    "El Biar",
    "Bouzareah",
    "Birkhadem",
    "El Harrach",
    "Baraki",
    "Oued Smar",
    "Bourouba",
    "Hussein Dey",
    "Kouba",
    "Bach Djerrah",
    "Dar El Beïda",
    "Bab Ezzouar",
    "Ben Aknoun",
    "Dely Ibrahim",
    "El Hammamet",
    "Raïs Hamidou",
    "Djasr Kasentina",
    "El Mouradia",
    "Hydra",
    "Mohammadia",
    "Bordj El Kiffan",
    "El Magharia",
    "Beni Messous",
    "Les Eucalyptus",
    "Birtouta",
    "Tessala El Merdja",
    "Ouled Chebel",
    "Sidi Moussa",
    "Aïn Taya",
    "Bordj El Bahri",
    "Marsa",
    "H'raoua",
    "Rouïba",
    "Reghaïa",
    "Aïn Benian",
    "Staouéli",
    "Zéralda",
    "Mahelma",
    "Rahmania",
    "Souidania",
    "Chéraga",
    "Ouled Fayet",
    "El Achour",
    "Draria",
    "Douéra",
    "Baba Hassen",
    "Khraïcia",
    "Saoula",
  ],

  Djelfa: [
    "Djelfa",
    "Moudjbara",
    "El Guedid",
    "Hassi Bahbah",
    "Aïn El Ibel",
    "Dar Chioukh",
    "Messaad",
    "Birine",
    "Bouira Lahdab",
    "Zaccar",
    "El Khemis",
    "Sed Rahal",
    "Benhar",
    "Sidi Baizid",
    "Mliliha",
    "El Idrissia",
    "Douis",
    "Hassi Fedoul",
    "Hassi El Euch",
    "Messad",
    "Guettara",
    "Aïn Maabed",
    "Sidi Laadjel",
    "Faidh El Botma",
    "Birine",
    "Zaafrane",
    "Aïn Chouhada",
    "Oum Laadham",
    "Deldoul",
    "Aïn Feka",
    "Charef",
    "Beni Yagoub",
    "Had Sahary",
    "Guernini",
    "Selmana",
    "Ain Oussera",
  ],

  Jijel: [
    "Jijel",
    "Eraguene",
    "El Aouana",
    "Ziama Mansouriah",
    "Taher",
    "Emir Abdelkader",
    "Chekfa",
    "Chahna",
    "El Milia",
    "Sidi Maarouf",
    "Settara",
    "El Ancer",
    "Sidi Abdelaziz",
    "Kaous",
    "Ghebala",
    "Bouraoui Belhadef",
    "Djimla",
    "Selma Benziada",
    "Boussif Ouled Askeur",
    "El Kennar Nouchfi",
    "Ouled Yahia Khedrouche",
    "Boudria Beni Yadjis",
    "Kemir Oued Adjoul",
    "Texenna",
    "Djemaa Beni Habibi",
    "Bordj Tahar",
    "Ouled Rabah",
  ],

  Sétif: [
    "Sétif",
    "Aïn El Kebira",
    "Beni Aziz",
    "Ouled Sidi Ahmed",
    "Boutaleb",
    "Aïn Roua",
    "Draa Kebila",
    "Bir El Arch",
    "Bougaa",
    "El Eulma",
    "Djemila",
    "Beni Ourtilane",
    "Rosfa",
    "Ouled Addouane",
    "Belaa",
    "Aïn Lahdjar",
    "Bousselam",
    "Ain Oulmene",
    "Kasr El Abtal",
    "Beni Fouda",
    "Tachouda",
    "Bouandas",
    "Mezloug",
    "Aïn Arnat",
    "Dehamcha",
    "Babor",
    "Guidjel",
    "Aïn Abessa",
    "Hammam Guergour",
    "Ait Naoual Mezada",
    "Beidha Bordj",
    "El Ouldja",
    "Tizi Nbechar",
    "Salah Bey",
    "Aïn Azal",
    "Guenzet",
    "Talaifacene",
    "Beni Chebana",
    "Ouled Tebben",
    "Hamma",
    "Maaouia",
    "Aïn Legradj",
    "Aïn Sebt",
    "Harbil",
    "El Ouricia",
    "Tella",
    "Aït Tizi",
    "Maouaklane",
    "Guellal",
    "Aïn Azel",
    "Guelta Zerka",
    "Oued El Barad",
    "Taya",
    "El Guelb El Kebir",
    "Boukaâ",
    "Bir Haddada",
    "Serdj El Ghoul",
    "Amoucha",
    "Tizi",
  ],

  Saïda: [
    "Saïda",
    "Doui Thabet",
    "Aïn El Hadjar",
    "Ouled Khaled",
    "Moulay Larbi",
    "Youb",
    "Hounet",
    "Sidi Amar",
    "Sidi Boubekeur",
    "El Hassasna",
    "Maamora",
    "Sidi Ahmed",
    "Aïn Sekhouna",
    "Ouled Brahim",
    "Tircine",
    "Aïn Soltane",
  ],

  Skikda: [
    "Skikda",
    "Aïn Zouit",
    "El Hadaiek",
    "Azzaba",
    "Djendel Saadi Mohamed",
    "Collo",
    "Beni Zid",
    "Kerkera",
    "Ouled Attia",
    "Oued Zehour",
    "Zitouna",
    "El Harrouch",
    "Zerdazas",
    "Ouled Hbaba",
    "Sidi Mezghiche",
    "Emdjez Edchich",
    "Beni Oulbane",
    "Aïn Cherchar",
    "Bekkouche Lakhdar",
    "Beni Bachir",
    "Salah Bouchaour",
    "Tamalous",
    "Aïn Kechra",
    "Oum Toub",
    "Benazouz",
    "Aïn Bouziane",
    "Ramdane Djamel",
    "Bouchtata",
    "Ouled Attia",
    "El Ghedir",
    "Hammadi Krouma",
    "El Marsa",
    "Cheraia",
    "Kanoua",
    "Es Sebt",
    "Laroui",
    "Fil Fila",
    "Tamalous",
  ],

  "Sidi Bel Abbès": [
    "Sidi Bel Abbès",
    "Tessala",
    "Sidi Brahim",
    "Mostefa Ben Brahim",
    "Telagh",
    "Aïn El Berd",
    "Amarnas",
    "Tilmouni",
    "Sidi Lahcene",
    "Aïn Thrid",
    "Merine",
    "Ras El Ma",
    "Tabia",
    "Sfissef",
    "Sidi Khaled",
    "Ain Tindamine",
    "Moulay Slissen",
    "El Haçaiba",
    "Sidi Yacoub",
    "Sidi Ali Boussidi",
    "Badredine El Mokrani",
    "Marhoum",
    "Tafissour",
    "Redjem Demouche",
    "Sidi Hamadouche",
    "Makedra",
    "Tenira",
    "Moulay Slissen",
    "Bir El Hammam",
    "Taoudmout",
    "Sidi Ali Benyoub",
    "Sehala Thaoura",
    "Ain Kada",
    "Hassi Zehana",
    "Touahria",
    "Chetouane Belaila",
    "Boudjebaa El Bordj",
    "Belarbi",
    "Lamtar",
    "Benachiba Chelia",
    "Hassi Dahou",
    "Teghalimet",
    "Zerouala",
    "Oued Sefioun",
    "Dhaya",
    "Mezaourou",
    "Sidi Chaib",
    "Ras El Ma",
    "Aïn Adden",
    "Oued Taourira",
    "Sidi Khaled",
  ],

  Annaba: [
    "Annaba",
    "Berrahal",
    "El Hadjar",
    "Aïn Berda",
    "El Bouni",
    "Oued El Aneb",
    "Cheurfa",
    "Seraïdi",
    "Sidi Amar",
    "Treat",
    "El Eulma",
  ],

  Guelma: [
    "Guelma",
    "Nechmaya",
    "Bouati Mahmoud",
    "Oued Zenati",
    "Tamlouka",
    "Oued Fragha",
    "Aïn Ben Beida",
    "Khezaras",
    "Aïn Makhlouf",
    "Aïn Larbi",
    "Fedjoudj",
    "Hammam Debagh",
    "Bouchegouf",
    "Heliopolis",
    "Aïn Sandel",
    "Medjez Amar",
    "Bordj Sabath",
    "Hammam N'Bails",
    "Aïn Reggada",
    "Oued Cheham",
    "Djeballah Khemissi",
    "Belkheir",
    "Sellaoua Announa",
    "Dahouara",
    "Ben Djerrah",
    "Bouhamdane",
    "Khezara",
    "Bouhachana",
    "El Fedjoudj",
    "Guelaat Bou Sbaa",
    "Houari Boumediene",
    "Ras El Agba",
  ],

  Constantine: [
    "Constantine",
    "Hamma Bouziane",
    "Aïn Smara",
    "Didouche Mourad",
    "El Khroub",
    "Ouled Rahmoun",
    "Zighoud Youcef",
    "Aïn Abid",
    "Ibn Ziad",
    "Beni Hamiden",
    "Ouled Rahmoune",
    "El Meridj",
    "Ben Badis",
    "Messaoud Boudjriou",
  ],

  Médéa: [
    "Médéa",
    "Ouzera",
    "Ouled Maaref",
    "Aïn Boucif",
    "Ouled Hellal",
    "Tamesguida",
    "El Azizia",
    "Souagui",
    "Ouled Bouachra",
    "Derrag",
    "El Omaria",
    "Ksar El Boukhari",
    "Ouled Antar",
    "Boughezoul",
    "Aïssaouia",
    "Sidi Naamane",
    "Chellalet El Adhaoura",
    "Bir Ben Laabed",
    "El Guelb El Kebir",
    "Bouaiche",
    "Aïn Ouksir",
    "Chahbounia",
    "Benchicao",
    "Djouab",
    "Sidi Ziane",
    "Sidi Errabia",
    "Tablat",
    "Baata",
    "Maghraoua",
    "Tafraout",
    "Beni Slimane",
    "Rebaia",
    "Aziz",
    "Tizi Mahdi",
    "Kef Lakhdar",
    "Cheniguel",
    "Oued Harbil",
    "Seghouane",
    "Sidi Zahar",
    "Bouaichoune",
    "Aïn Boucif",
    "Mezerana",
    "Mihoub",
    "Berrouaghia",
    "Boghar",
    "Deux Bassins",
    "Draa Esmar",
    "Saneg",
    "El Hamdania",
    "Zoubiria",
    "Khams Djouamaa",
    "Sedraya",
    "Bouchrahil",
    "Si Mahdjoub",
    "Moudjbar",
    "Aïn Boucif",
    "Sidi Damed",
    "Hannacha",
    "Oued Harbil",
    "Ouled Deide",
    "Bouaiche",
    "Ouled Brahim",
  ],

  Mostaganem: [
    "Mostaganem",
    "Sayada",
    "Fornaka",
    "Stidia",
    "Aïn Nouissy",
    "Hassi Mameche",
    "Aïn Tedles",
    "Sidi Ali",
    "Kheir Eddine",
    "Sidi Lakhdar",
    "Achaacha",
    "Khadra",
    "Bouguirat",
    "Sirat",
    "Aïn Boudinar",
    "Mesra",
    "Mansourah",
    "Souaflia",
    "Oued El Kheir",
    "Sidi Belattar",
    "Hadjadj",
    "Nekmaria",
    "Sidi Ali",
    "Tazgait",
    "Aïn Sidi Cherif",
    "Touahria",
    "El Hassiane",
    "Othmania",
    "Safsaf",
    "Benabdelmalek Ramdane",
    "Oued Charef",
  ],

  "M'Sila": [
    "M'Sila",
    "Maadid",
    "Hammam Dalaa",
    "Ouled Derradj",
    "Tarmount",
    "Mtarfa",
    "Khoubana",
    "Mcif",
    "Chellal",
    "Ouled Madhi",
    "Magra",
    "Berhoum",
    "Aïn El Hadjel",
    "Aïn Rich",
    "Bou Saâda",
    "Ouled Sidi Brahim",
    "Sidi Aïssa",
    "Aïn El Melh",
    "Hammam Dhala",
    "Ouanougha",
    "Benzouh",
    "Aïn Khadra",
    "Ouled Addi Guebala",
    "Belaiba",
    "Sidi Hadjeres",
    "Tamsa",
    "Bir Foda",
    "Mohamed Boudiaf",
    "Slim",
    "Ain Fares",
    "Aïn El Hadjel",
    "Ouled Slimane",
    "Ain Errich",
    "Dehahna",
    "Bou Saâda",
  ],

  Mascara: [
    "Mascara",
    "Bou Hanifia",
    "Tizi",
    "Aïn Ferah",
    "Ghriss",
    "Froha",
    "Matemore",
    "Bouhanifia",
    "Hacine",
    "Maoussa",
    "Sig",
    "Oued El Abtal",
    "Aïn Fares",
    "Ghriss",
    "Mohammadia",
    "Sidi Kada",
    "Tighennif",
    "Ferraguig",
    "El Bordj",
    "Aïn Fekan",
    "Oued Taria",
    "Sehailia",
    "Sidi Abdelmoumene",
    "Aïn Fares",
    "Guerdjoum",
    "Aouf",
    "Alaimia",
    "El Menaouer",
    "Oued El Abtal",
    "Gharrous",
    "Mamounia",
    "Guettena",
    "Aïn Fares",
    "Khalouia",
    "El Ghomri",
    "Sedra",
    "Mocta Douz",
    "Benian",
    "Sidi Boussaid",
    "Ras Ain Amirouche",
    "Zahana",
    "Mohammadia",
    "Sidi Abdeldjebar",
    "Nesmot",
    "Aïn Ferah",
    "Chorfa",
    "El Gaada",
    "Aïn Ferah",
  ],

  Ouargla: [
    "Ouargla",
    "Rouissat",
    "Aïn Beïda",
    "N'Goussa",
    "Hassi Messaoud",
    "Hassi Ben Abdallah",
    "Sidi Khouiled",
    "Touggourt",
    "Nezla",
    "Zaouia El Abidia",
    "El Alia",
    "Tebesbest",
    "El Hadjira",
    "Taibet",
    "Temacine",
    "Blidet Amor",
    "Megarine",
    "Sidi Slimane",
    "Benaceur",
    "M'Naguer",
    "El Borma",
    "Hassi Khelifa",
  ],

  Oran: [
    "Oran",
    "Gdyel",
    "Bir El Djir",
    "Hassi Bounif",
    "Es Sénia",
    "Arzew",
    "Bethioua",
    "Marsat El Hadjadj",
    "Aïn El Türk",
    "El Ancar",
    "Oued Tlélat",
    "Tafraoui",
    "Sidi Chami",
    "Boufatis",
    "Mers El Kébir",
    "Bousfer",
    "El Kerma",
    "El Braya",
    "Hassi Ben Okba",
    "Ben Freha",
    "Hassi Mefsoukh",
    "Sidi Ben Yebka",
    "Boutlélis",
    "Aïn El Kerma",
    "Aïn El Bia",
  ],

  "El Bayadh": [
    "El Bayadh",
    "Rogassa",
    "Stitten",
    "Brezina",
    "Ghassoul",
    "Boualem",
    "El Abiodh Sidi Cheikh",
    "Aïn El Orak",
    "Arbaouat",
    "Bougtoub",
    "El Mehara",
    "Tousmouline",
    "El Kheiter",
    "Kef El Ahmar",
    "Boussemghoun",
    "Chellala",
    "Krakda",
    "El Bnoud",
    "Cheguig",
    "Sidi Ameur",
    "El Biodh",
    "Labiodh Sidi Cheikh",
  ],

  Illizi: [
    "Illizi",
    "Djanet",
    "Debdeb",
    "Bordj Omar Driss",
    "Bordj El Haouès",
    "In Amenas",
  ],

  "Bordj Bou Arréridj": [
    "Bordj Bou Arréridj",
    "Aïn Taghrout",
    "Bordj Zemoura",
    "Mansoura",
    "El Achir",
    "Medjana",
    "El Hamadia",
    "Bordj Ghedir",
    "Djaafra",
    "El Main",
    "Ouled Brahem",
    "El Anseur",
    "Tesmart",
    "Aïn Tesra",
    "Bir Kasdali",
    "Ksour",
    "Ouled Dahmane",
    "Hasnaoua",
    "Khelil",
    "Sidi Embarek",
    "El Mehir",
    "Belimour",
    "Taglait",
    "Colla",
    "Tixter",
    "Rabta",
    "Haraza",
    "Ghilassa",
    "Tefreg",
    "Ras El Oued",
    "Bordj Bou Arreridj",
    "Teniet En Nasr",
    "Bou Aouda",
  ],

  Boumerdès: [
    "Boumerdès",
    "Boudouaou",
    "Aïn Benian",
    "Ouled Moussa",
    "Boudouaou El Bahri",
    "Tidjelabine",
    "Naciria",
    "Djinet",
    "Isser",
    "Zemmouri",
    "Si Mustapha",
    "Souk El Had",
    "Beni Amrane",
    "Corso",
    "Ouled Aïssa",
    "Larbatache",
    "Chabet El Ameur",
    "Khemis El Khechna",
    "Thenia",
    "Timezrit",
    "Bordj Menaïel",
    "Baghlia",
    "Sidi Daoud",
    "Ouled Hedadj",
    "Leghata",
    "Afir",
    "Dellys",
    "El Kharrouba",
    "Ammal",
    "Bouzegza Keddara",
    "Taourga",
    "Hammedi",
    "Benchoud",
  ],

  "El Tarf": [
    "El Tarf",
    "Bouhadjar",
    "Ben M'Hidi",
    "Bougous",
    "El Kala",
    "Aïn El Assel",
    "El Aioun",
    "Bouteldja",
    "Besbes",
    "Asfour",
    "Echatt",
    "Zerizer",
    "Zitouna",
    "Aïn Kerma",
    "Oued Zitoun",
    "Hammam Beni Salah",
    "Raml Souk",
    "Lac des Oiseaux",
    "Chefia",
    "Drean",
    "Chihani",
    "Chebaita Mokhtar",
    "Berrihane",
    "Souarekh",
  ],

  Tindouf: ["Tindouf", "Oum El Assel"],

  Tissemsilt: [
    "Tissemsilt",
    "Bordj Bou Naama",
    "Theniet El Had",
    "Lazharia",
    "Beni Chaib",
    "Lardjem",
    "Melaab",
    "Sidi Lantri",
    "Bordj El Emir Abdelkader",
    "Layoune",
    "Khemisti",
    "Ouled Bessem",
    "Ammari",
    "Youssoufia",
    "Sidi Boutouchent",
    "Larbaa",
    "Maacem",
    "Sidi Abed",
    "Tamalaht",
    "Sidi Slimane",
    "Boucaid",
    "Lazharia",
  ],

  "El Oued": [
    "El Oued",
    "Robbah",
    "Oued El Alenda",
    "Bayadha",
    "Nakhla",
    "Guemar",
    "Kouinine",
    "Reguiba",
    "Hamraia",
    "Taghzout",
    "Debila",
    "Hassani Abdelkrim",
    "Hassi Khelifa",
    "Taleb Larbi",
    "Douar El Ma",
    "Sidi Aoun",
    "Trifaoui",
    "Magrane",
    "Beni Guecha",
    "Ourmas",
    "Still",
    "M'Rara",
    "Sidi Khelil",
    "Tendla",
    "El Ogla",
    "Mih Ouansa",
    "Sidi Amrane",
    "Oum Touyour",
    "Taleb Larbi",
  ],

  Khenchela: [
    "Khenchela",
    "Mtoussa",
    "Kais",
    "Baghai",
    "El Hamma",
    "Aïn Touila",
    "Taouzianat",
    "Bouhmama",
    "El Oueldja",
    "Remila",
    "Cherchar",
    "Djellal",
    "Babar",
    "Tamza",
    "Ensigha",
    "Ouled Rechache",
    "El Mahmal",
    "M'Sara",
    "Yabous",
    "Khirane",
    "Chelia",
  ],

  "Souk Ahras": [
    "Souk Ahras",
    "Sedrata",
    "Mechroha",
    "Ouled Driss",
    "Tiffech",
    "Zaarouria",
    "Taoura",
    "Drea",
    "Haddada",
    "Khedara",
    "Merahna",
    "Ouled Moumen",
    "Birr Bouhouche",
    "Mdaourouch",
    "Oum El Adhaim",
    "Aïn Zana",
    "Aïn Soltane",
    "Ouillen",
    "Terraguelt",
    "Zouabi",
    "Ragouba",
    "Khemissa",
    "Oued Keberit",
    "Safel El Ouiden",
    "M'Daourouche",
    "Sidi Fredj",
  ],

  Tipaza: [
    "Tipaza",
    "Menaceur",
    "Larhat",
    "Douaouda",
    "Bourkika",
    "Khemisti",
    "Aghbal",
    "Hadjout",
    "Sidi Amar",
    "Gouraya",
    "Nador",
    "Chaïba",
    "Aïn Tagourait",
    "Cherchell",
    "Damous",
    "Merad",
    "Fouka",
    "Bou Ismaïl",
    "Ahmer El Aïn",
    "Bou Haroun",
    "Sidi Ghilès",
    "Messelmoun",
    "Sidi Rached",
    "Kolea",
    "Attatba",
    "Sidi Semiane",
    "Beni Milleuk",
    "Hadjerat Ennous",
  ],

  Mila: [
    "Mila",
    "Ferdjioua",
    "Chelghoum Laid",
    "Oued Athmania",
    "Aïn Beida Harriche",
    "Telerghma",
    "Oued Seguen",
    "Tadjenanet",
    "Benyahia Abderrahmane",
    "Sidi Merouane",
    "Ahmed Rachedi",
    "Ouled Khellouf",
    "Tiberguent",
    "Zeghaia",
    "Aïn Mellouk",
    "Rouached",
    "Terrai Bainen",
    "Tessala Lemtaï",
    "Grarem Gouga",
    "Bouhatem",
    "Hamala",
    "Aïn Tine",
    "Elayadi Barbes",
    "Sidi Khelifa",
    "Yahia Beni Guecha",
    "Tassadane Haddada",
    "Derradji Bousselah",
    "Amira Arras",
    "Minar Zarza",
    "Oued Endja",
    "Chigara",
  ],

  "Aïn Defla": [
    "Aïn Defla",
    "Miliana",
    "Boumedfaa",
    "Khemis Miliana",
    "Hammam Righa",
    "Aïn Lechiakh",
    "El Amra",
    "Aïn Benian",
    "Hoceinia",
    "Aïn Soltane",
    "Tarik Ibn Ziad",
    "Bordj Emir Khaled",
    "Aïn Torki",
    "Sidi Lakhdar",
    "Ben Allal",
    "Aïn Benian",
    "Hoceinia",
    "Djendel",
    "Oued Chorfa",
    "Aïn Bouyahia",
    "El Attaf",
    "Ouled Abbès",
    "Beni Rached",
    "Djemaa Ouled Cheikh",
    "Bathia",
    "Tacheta Zougagha",
    "Arib",
    "Mekhatria",
    "Djelida",
    "El Abadia",
    "Tiberkanine",
    "Aïn Defla",
    "Zeddine",
    "El Maine",
    "Rouina",
    "Djemaa Ouled Cheikh",
    "Bourached",
  ],

  Naâma: [
    "Naâma",
    "Mechria",
    "Aïn Sefra",
    "Tiout",
    "Sfissifa",
    "Moghrar",
    "Assela",
    "Djeniane Bourzeg",
    "Aïn Ben Khelil",
    "Makman Ben Amer",
    "Kasdir",
    "El Biod",
  ],

  "Aïn Témouchent": [
    "Aïn Témouchent",
    "Chaabet El Leham",
    "Aïn Kihal",
    "Hammam Bou Hadjar",
    "Bou Zedjar",
    "Oued Berkeche",
    "Aghlal",
    "Terga",
    "Aïn El Arbaa",
    "Tamzoura",
    "Chentouf",
    "Sidi Boumediene",
    "Sidi Ben Adda",
    "Ouled Boudjemaa",
    "Oued Sabah",
    "Ouled Kihal",
    "Beni Saf",
    "Sidi Safi",
    "Oulhaça El Gheraba",
    "Souk El Khemis",
    "Sidi Ouriache",
    "M'Ssaid",
    "Hassi El Ghella",
    "Hassasna",
    "Zaouia",
    "El Amria",
    "El Malah",
    "El Emir Abdelkader",
  ],

  Ghardaïa: [
    "Ghardaïa",
    "El Menia",
    "Dhayet Bendhahoua",
    "Berriane",
    "Metlili",
    "El Atteuf",
    "Zelfana",
    "Sebseb",
    "Bounoura",
    "Hassi Fehal",
    "Hassi Gara",
    "Mansoura",
    "Guerrara",
  ],

  Relizane: [
    "Relizane",
    "Oued Rhiou",
    "Belhacel",
    "Mazouna",
    "Zemmoura",
    "Sidi M'Hamed Ben Ali",
    "Mendes",
    "Lahlef",
    "Djidiouia",
    "Yellel",
    "Oued Essalem",
    "Ouarizane",
    "Mazouna",
    "Kalaa",
    "Aïn Tarek",
    "Sidi Saada",
    "Ouled Aiche",
    "Sidi Lazreg",
    "El Hamadna",
    "Beni Dergoun",
    "Sidi M'Hamed Benaouda",
    "Harchoune",
    "Oued El Djemaa",
    "Aïn Rahma",
    "Yellel",
    "Beni Zentis",
    "Ramka",
    "Menaceur",
    "El Matmar",
    "Sidi Khettab",
    "Ammi Moussa",
    "Zemmoura",
    "Beni Dergoun",
    "Had Echkala",
    "El Guettar",
    "Hamri",
    "El Ouldja",
  ],
};
