export const WILAYAS = [
  "Adrar",
  "Chlef",
  "Laghouat",
  "Oum El Bouaghi",
  "Batna",
  "Béjaïa",
  "Biskra",
  "Béchar",
  "Blida",
  "Bouira",
  "Tamanrasset",
  "Tébessa",
  "Tlemcen",
  "Tiaret",
  "Tizi Ouzou",
  "Alger",
  "Djelfa",
  "Jijel",
  "Sétif",
  "Saïda",
  "Skikda",
  "Sidi Bel Abbès",
  "Annaba",
  "Guelma",
  "Constantine",
  "Médéa",
  "Mostaganem",
  "M'Sila",
  "Mascara",
  "Ouargla",
  "Oran",
  "El Bayadh",
  "Illizi",
  "Bordj Bou Arréridj",
  "Boumerdès",
  "El Tarf",
  "Tindouf",
  "Tissemsilt",
  "El Oued",
  "Khenchela",
  "Souk Ahras",
  "Tipaza",
  "Mila",
  "Aïn Defla",
  "Naâma",
  "Aïn Témouchent",
  "Ghardaïa",
  "Relizane",
  "Timimoun",
  "Bordj Badji Mokhtar",
  "Ouled Djellal",
  "Béni Abbès",
  "In Salah",
  "In Guezzam",
  "Touggourt",
  "Djanet",
  "El M'Ghair",
  "El Meniaa",
] as const;

export const SPECIALITES = [
  "Droit administratif",
  "Droit bancaire et financier",
  "Droit civil",
  "Droit commercial et des affaires",
  "Droit de la consommation",
  "Droit de la famille",
  "Droit de la propriété intellectuelle et industrielle",
  "Droit de l'environnement",
  "Droit de l'immobilier",
  "Droit des assurances",
  "Droit des étrangers et immigration",
  "Droit des nouvelles technologies",
  "Droit des sociétés",
  "Droit du travail et social",
  "Droit fiscal",
  "Droit international",
  "Droit maritime",
  "Droit médical",
  "Droit pénal",
  "Droit public",
  "Droit routier",
] as const;

export const URGENCE_OPTIONS = [
  { value: "normal", label: "Normal (48h)", multiplicateur: 1 },
  { value: "urgent", label: "Urgent (24h)", multiplicateur: 1.3 },
  { value: "tres_urgent", label: "Très urgent (6h)", multiplicateur: 1.6 },
] as const;

export const TARIF_RANGES = [
  { label: "Moins de 3 000 DA", min: 0, max: 3000 },
  { label: "3 000 - 5 000 DA", min: 3000, max: 5000 },
  { label: "5 000 - 8 000 DA", min: 5000, max: 8000 },
  { label: "Plus de 8 000 DA", min: 8000, max: 999999 },
] as const;

export const COUNTRIES = [
  { id: "dz", code: "213", name: "Algérie", flag: "🇩🇿" },
  { id: "fr", code: "33", name: "France", flag: "🇫🇷" },
  { id: "be", code: "32", name: "Belgique", flag: "🇧🇪" },
  { id: "ch", code: "41", name: "Suisse", flag: "🇨🇭" },
  { id: "lu", code: "352", name: "Luxembourg", flag: "🇱🇺" },
  { id: "ca", code: "1", name: "Canada", flag: "🇨🇦" },
  { id: "us", code: "1", name: "États-Unis", flag: "🇺🇸" },
  { id: "gb", code: "44", name: "Royaume-Uni", flag: "🇬🇧" },
  { id: "de", code: "49", name: "Allemagne", flag: "🇩🇪" },
  { id: "es", code: "34", name: "Espagne", flag: "🇪🇸" },
  { id: "it", code: "39", name: "Italie", flag: "🇮🇹" },
  { id: "nl", code: "31", name: "Pays-Bas", flag: "🇳🇱" },
  { id: "pt", code: "351", name: "Portugal", flag: "🇵🇹" },
  { id: "se", code: "46", name: "Suède", flag: "🇸🇪" },
  { id: "no", code: "47", name: "Norvège", flag: "🇳🇴" },
  { id: "dk", code: "45", name: "Danemark", flag: "🇩🇰" },
  { id: "fi", code: "358", name: "Finlande", flag: "🇫🇮" },
  { id: "at", code: "43", name: "Autriche", flag: "🇦🇹" },
  { id: "gr", code: "30", name: "Grèce", flag: "🇬🇷" },
  { id: "pl", code: "48", name: "Pologne", flag: "🇵🇱" },
  { id: "ma", code: "212", name: "Maroc", flag: "🇲🇦" },
  { id: "tn", code: "216", name: "Tunisie", flag: "🇹🇳" },
  { id: "ly", code: "218", name: "Libye", flag: "🇱🇾" },
  { id: "eg", code: "20", name: "Égypte", flag: "🇪🇬" },
  { id: "mr", code: "222", name: "Mauritanie", flag: "🇲🇷" },
  { id: "sn", code: "221", name: "Sénégal", flag: "🇸🇳" },
  { id: "ci", code: "225", name: "Côte d'Ivoire", flag: "🇨🇮" },
  { id: "cm", code: "237", name: "Cameroun", flag: "🇨🇲" },
  { id: "cd", code: "243", name: "RD Congo", flag: "🇨🇩" },
  { id: "cg", code: "242", name: "Congo", flag: "🇨🇬" },
  { id: "ga", code: "241", name: "Gabon", flag: "🇬🇦" },
  { id: "ng", code: "234", name: "Nigéria", flag: "🇳🇬" },
  { id: "gh", code: "233", name: "Ghana", flag: "🇬🇭" },
  { id: "sa", code: "966", name: "Arabie Saoudite", flag: "🇸🇦" },
  { id: "ae", code: "971", name: "Émirats Arabes Unis", flag: "🇦🇪" },
  { id: "qa", code: "974", name: "Qatar", flag: "🇶🇦" },
  { id: "kw", code: "965", name: "Koweït", flag: "🇰🇼" },
  { id: "bh", code: "973", name: "Bahreïn", flag: "🇧🇭" },
  { id: "om", code: "968", name: "Oman", flag: "🇴🇲" },
  { id: "jo", code: "962", name: "Jordanie", flag: "🇯🇴" },
  { id: "lb", code: "961", name: "Liban", flag: "🇱🇧" },
  { id: "sy", code: "963", name: "Syrie", flag: "🇸🇾" },
  { id: "iq", code: "964", name: "Irak", flag: "🇮🇶" },
  { id: "tr", code: "90", name: "Turquie", flag: "🇹🇷" },
  { id: "ru", code: "7", name: "Russie", flag: "🇷🇺" },
  { id: "cn", code: "86", name: "Chine", flag: "🇨🇳" },
  { id: "jp", code: "81", name: "Japon", flag: "🇯🇵" },
  { id: "in", code: "91", name: "Inde", flag: "🇮🇳" },
  { id: "br", code: "55", name: "Brésil", flag: "🇧🇷" },
  { id: "mx", code: "52", name: "Mexique", flag: "🇲🇽" },
  { id: "au", code: "61", name: "Australie", flag: "🇦🇺" },
  { id: "za", code: "27", name: "Afrique du Sud", flag: "🇿🇦" },
] as const;

export const LOCATION_TO_PHONE_CODE: Record<string, string> = {
  algerie: "213",
  france: "33",
  belgique: "32",
  suisse: "41",
  luxembourg: "352",
  canada: "1",
  "etats-unis": "1",
  "royaume-uni": "44",
  allemagne: "49",
  espagne: "34",
  italie: "39",
  "pays-bas": "31",
  portugal: "351",
  suede: "46",
  norvege: "47",
  danemark: "45",
  finlande: "358",
  autriche: "43",
  grece: "30",
  pologne: "48",
  maroc: "212",
  tunisie: "216",
  libye: "218",
  egypte: "20",
  mauritanie: "222",
  senegal: "221",
  "cote-divoire": "225",
  cameroun: "237",
  "republique-democratique-du-congo": "243",
  congo: "242",
  gabon: "241",
  nigeria: "234",
  ghana: "233",
  "arabie-saoudite": "966",
  "emirats-arabes-unis": "971",
  qatar: "974",
  koweit: "965",
  bahrein: "973",
  oman: "968",
  jordanie: "962",
  liban: "961",
  syrie: "963",
  irak: "964",
  turquie: "90",
  russie: "7",
  chine: "86",
  japon: "81",
  inde: "91",
  bresil: "55",
  mexique: "52",
  australie: "61",
  "afrique-du-sud": "27",
};

export const LOCATION = [
  { value: "algerie", label: "Algérie" },
  { value: "afghanistan", label: "Afghanistan" },
  { value: "afrique-du-sud", label: "Afrique du Sud" },
  { value: "albanie", label: "Albanie" },
  { value: "allemagne", label: "Allemagne" },
  { value: "andorre", label: "Andorre" },
  { value: "angola", label: "Angola" },
  { value: "antigua-et-barbuda", label: "Antigua-et-Barbuda" },
  { value: "arabie-saoudite", label: "Arabie Saoudite" },
  { value: "argentine", label: "Argentine" },
  { value: "armenie", label: "Arménie" },
  { value: "australie", label: "Australie" },
  { value: "autriche", label: "Autriche" },
  { value: "azerbaidjan", label: "Azerbaïdjan" },
  { value: "bahamas", label: "Bahamas" },
  { value: "bahrein", label: "Bahreïn" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "barbade", label: "Barbade" },
  { value: "belarus", label: "Bélarus" },
  { value: "belgique", label: "Belgique" },
  { value: "belize", label: "Belize" },
  { value: "benin", label: "Bénin" },
  { value: "bhoutan", label: "Bhoutan" },
  { value: "bolivie", label: "Bolivie" },
  { value: "bosnie-herzegovine", label: "Bosnie-Herzégovine" },
  { value: "botswana", label: "Botswana" },
  { value: "bresil", label: "Brésil" },
  { value: "brunei", label: "Brunéi" },
  { value: "bulgarie", label: "Bulgarie" },
  { value: "burkina-faso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cabo-verde", label: "Cabo Verde" },
  { value: "cambodge", label: "Cambodge" },
  { value: "cameroun", label: "Cameroun" },
  { value: "canada", label: "Canada" },
  { value: "chili", label: "Chili" },
  { value: "chine", label: "Chine" },
  { value: "chypre", label: "Chypre" },
  { value: "colombie", label: "Colombie" },
  { value: "comores", label: "Comores" },
  { value: "congo", label: "Congo" },
  { value: "costa-rica", label: "Costa Rica" },
  { value: "cote-divoire", label: "Côte d'Ivoire" },
  { value: "croatie", label: "Croatie" },
  { value: "cuba", label: "Cuba" },
  { value: "danemark", label: "Danemark" },
  { value: "djibouti", label: "Djibouti" },
  { value: "dominique", label: "Dominique" },
  { value: "egypte", label: "Égypte" },
  { value: "emirats-arabes-unis", label: "Émirats Arabes Unis" },
  { value: "equateur", label: "Équateur" },
  { value: "erythree", label: "Érythrée" },
  { value: "espagne", label: "Espagne" },
  { value: "eswatini", label: "Eswatini" },
  { value: "estonie", label: "Estonie" },
  { value: "etats-unis", label: "États-Unis" },
  { value: "ethiopie", label: "Éthiopie" },
  { value: "fidji", label: "Fidji" },
  { value: "finlande", label: "Finlande" },
  { value: "france", label: "France" },
  { value: "gabon", label: "Gabon" },
  { value: "gambie", label: "Gambie" },
  { value: "georgie", label: "Géorgie" },
  { value: "ghana", label: "Ghana" },
  { value: "grece", label: "Grèce" },
  { value: "grenade", label: "Grenade" },
  { value: "guatemala", label: "Guatemala" },
  { value: "guinee", label: "Guinée" },
  { value: "guinee-bissau", label: "Guinée-Bissau" },
  { value: "guinee-equatoriale", label: "Guinée Équatoriale" },
  { value: "guyana", label: "Guyana" },
  { value: "haiti", label: "Haïti" },
  { value: "honduras", label: "Honduras" },
  { value: "hongrie", label: "Hongrie" },
  { value: "inde", label: "Inde" },
  { value: "indonesie", label: "Indonésie" },
  { value: "irak", label: "Irak" },
  { value: "iran", label: "Iran" },
  { value: "irlande", label: "Irlande" },
  { value: "islande", label: "Islande" },
  { value: "italie", label: "Italie" },
  { value: "jamaique", label: "Jamaïque" },
  { value: "japon", label: "Japon" },
  { value: "jordanie", label: "Jordanie" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "kenya", label: "Kenya" },
  { value: "kirghizistan", label: "Kirghizistan" },
  { value: "kiribati", label: "Kiribati" },
  { value: "koweit", label: "Koweït" },
  { value: "laos", label: "Laos" },
  { value: "lesotho", label: "Lesotho" },
  { value: "lettonie", label: "Lettonie" },
  { value: "liban", label: "Liban" },
  { value: "liberia", label: "Libéria" },
  { value: "libye", label: "Libye" },
  { value: "liechtenstein", label: "Liechtenstein" },
  { value: "lituanie", label: "Lituanie" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "macedoine-du-nord", label: "Macédoine du Nord" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malaisie", label: "Malaisie" },
  { value: "malawi", label: "Malawi" },
  { value: "maldives", label: "Maldives" },
  { value: "mali", label: "Mali" },
  { value: "malte", label: "Malte" },
  { value: "maroc", label: "Maroc" },
  { value: "marshall", label: "Îles Marshall" },
  { value: "maurice", label: "Maurice" },
  { value: "mauritanie", label: "Mauritanie" },
  { value: "mexique", label: "Mexique" },
  { value: "micronesie", label: "Micronésie" },
  { value: "moldavie", label: "Moldavie" },
  { value: "monaco", label: "Monaco" },
  { value: "mongolie", label: "Mongolie" },
  { value: "montenegro", label: "Monténégro" },
  { value: "mozambique", label: "Mozambique" },
  { value: "myanmar", label: "Myanmar" },
  { value: "namibie", label: "Namibie" },
  { value: "nauru", label: "Nauru" },
  { value: "nepal", label: "Népal" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "niger", label: "Niger" },
  { value: "nigeria", label: "Nigéria" },
  { value: "norvege", label: "Norvège" },
  { value: "nouvelle-zelande", label: "Nouvelle-Zélande" },
  { value: "oman", label: "Oman" },
  { value: "ouganda", label: "Ouganda" },
  { value: "ouzbekistan", label: "Ouzbékistan" },
  { value: "pakistan", label: "Pakistan" },
  { value: "palestine", label: "Palestine" },
  { value: "palaos", label: "Palaos" },
  { value: "panama", label: "Panama" },
  { value: "papouasie-nouvelle-guinee", label: "Papouasie-Nouvelle-Guinée" },
  { value: "paraguay", label: "Paraguay" },
  { value: "pays-bas", label: "Pays-Bas" },
  { value: "perou", label: "Pérou" },
  { value: "philippines", label: "Philippines" },
  { value: "pologne", label: "Pologne" },
  { value: "portugal", label: "Portugal" },
  { value: "qatar", label: "Qatar" },
  { value: "republique-centrafricaine", label: "République Centrafricaine" },
  {
    value: "republique-democratique-du-congo",
    label: "République Démocratique du Congo",
  },
  { value: "republique-dominicaine", label: "République Dominicaine" },
  { value: "republique-tcheque", label: "République Tchèque" },
  { value: "roumanie", label: "Roumanie" },
  { value: "royaume-uni", label: "Royaume-Uni" },
  { value: "russie", label: "Russie" },
  { value: "rwanda", label: "Rwanda" },
  { value: "saint-christophe-et-nieves", label: "Saint-Christophe-et-Niévès" },
  { value: "saint-marin", label: "Saint-Marin" },
  {
    value: "saint-vincent-et-grenadines",
    label: "Saint-Vincent-et-les-Grenadines",
  },
  { value: "sainte-lucie", label: "Sainte-Lucie" },
  { value: "salomon", label: "Îles Salomon" },
  { value: "salvador", label: "Salvador" },
  { value: "samoa", label: "Samoa" },
  { value: "sao-tome-et-principe", label: "Sao Tomé-et-Principe" },
  { value: "senegal", label: "Sénégal" },
  { value: "serbie", label: "Serbie" },
  { value: "seychelles", label: "Seychelles" },
  { value: "sierra-leone", label: "Sierra Leone" },
  { value: "singapour", label: "Singapour" },
  { value: "slovaquie", label: "Slovaquie" },
  { value: "slovenie", label: "Slovénie" },
  { value: "somalie", label: "Somalie" },
  { value: "soudan", label: "Soudan" },
  { value: "soudan-du-sud", label: "Soudan du Sud" },
  { value: "sri-lanka", label: "Sri Lanka" },
  { value: "suede", label: "Suède" },
  { value: "suisse", label: "Suisse" },
  { value: "suriname", label: "Suriname" },
  { value: "syrie", label: "Syrie" },
  { value: "tadjikistan", label: "Tadjikistan" },
  { value: "tanzanie", label: "Tanzanie" },
  { value: "tchad", label: "Tchad" },
  { value: "thailande", label: "Thaïlande" },
  { value: "timor-oriental", label: "Timor Oriental" },
  { value: "togo", label: "Togo" },
  { value: "tonga", label: "Tonga" },
  { value: "trinite-et-tobago", label: "Trinité-et-Tobago" },
  { value: "tunisie", label: "Tunisie" },
  { value: "turkmenistan", label: "Turkménistan" },
  { value: "turquie", label: "Turquie" },
  { value: "tuvalu", label: "Tuvalu" },
  { value: "ukraine", label: "Ukraine" },
  { value: "uruguay", label: "Uruguay" },
  { value: "vanuatu", label: "Vanuatu" },
  { value: "venezuela", label: "Venezuela" },
  { value: "vietnam", label: "Viêt Nam" },
  { value: "yemen", label: "Yémen" },
  { value: "zambie", label: "Zambie" },
  { value: "zimbabwe", label: "Zimbabwe" },
];

export const LANGUES = [
  "Arabe",
  "Français",
  "Anglais",
  "Tamazight",
  "Espagnol",
];

export const LANGUES_TRADUCTEUR = [
  "Arabe",
  "Français",
  "Anglais",
  "Tamazight",
  "Espagnol",
  "Allemand",
  "Russe",
  "Chinois",
  "Italien",
  "Turc",
];

export const GENRES = [
  { value: "homme", label: "M." },
  { value: "femme", label: "Mme" },
];
