export const WILAYAS = [
  "Adrar",
  "Chlef",
  "Laghouat",
  "Oum El Bouaghi",
  "Batna",
  "Béjaïa",
  "Biskra",
  "Béchar",
  "Blida",
  "Bouira",
  "Tamanrasset",
  "Tébessa",
  "Tlemcen",
  "Tiaret",
  "Tizi Ouzou",
  "Alger",
  "Djelfa",
  "Jijel",
  "Sétif",
  "Saïda",
  "Skikda",
  "Sidi Bel Abbès",
  "Annaba",
  "Guelma",
  "Constantine",
  "Médéa",
  "Mostaganem",
  "M'Sila",
  "Mascara",
  "Ouargla",
  "Oran",
  "El Bayadh",
  "Illizi",
  "Bordj Bou Arréridj",
  "Boumerdès",
  "El Tarf",
  "Tindouf",
  "Tissemsilt",
  "El Oued",
  "Khenchela",
  "Souk Ahras",
  "Tipaza",
  "Mila",
  "Aïn Defla",
  "Naâma",
  "Aïn Témouchent",
  "Ghardaïa",
  "Relizane",
  "Timimoun",
  "Bordj Badji Mokhtar",
  "Ouled Djellal",
  "Béni Abbès",
  "In Salah",
  "In Guezzam",
  "Touggourt",
  "Djanet",
  "El M'Ghair",
  "El Meniaa",
] as const;

export const SPECIALITES = [
  "droit-administratif",
  "droit-bancaire-et-financier",
  "droit-civil",
  "droit-commercial-et-des-affaires",
  "droit-de-la-consommation",
  "droit-de-la-famille",
  "droit-de-la-propriete-intellectuelle-et-industrielle",
  "droit-de-l-environnement",
  "droit-de-l-immobilier",
  "droit-des-assurances",
  "droit-des-etrangers-et-immigration",
  "droit-des-nouvelles-technologies",
  "droit-des-societes",
  "droit-du-travail-et-social",
  "droit-fiscal",
  "droit-international",
  "droit-maritime",
  "droit-medical",
  "droit-penal",
  "droit-public",
  "droit-routier",
] as const;

export const URGENCE_OPTIONS = [
  { value: "normal", label: "Normal (48h)", multiplicateur: 1 },
  { value: "urgent", label: "Urgent (24h)", multiplicateur: 1.3 },
  { value: "tres_urgent", label: "Très urgent (6h)", multiplicateur: 1.6 },
] as const;

export const TARIF_RANGES = [
  { label: "Moins de 3 000 DA", min: 0, max: 3000 },
  { label: "3 000 - 5 000 DA", min: 3000, max: 5000 },
  { label: "5 000 - 8 000 DA", min: 5000, max: 8000 },
  { label: "Plus de 8 000 DA", min: 8000, max: 999999 },
] as const;

export const COUNTRIES = [
  { id: "dz", code: "213", name: "Algérie", flag: "🇩🇿" },
  { id: "fr", code: "33", name: "France", flag: "🇫🇷" },
  { id: "be", code: "32", name: "Belgique", flag: "🇧🇪" },
  { id: "ch", code: "41", name: "Suisse", flag: "🇨🇭" },
  { id: "lu", code: "352", name: "Luxembourg", flag: "🇱🇺" },
  { id: "ca", code: "1", name: "Canada", flag: "🇨🇦" },
  { id: "us", code: "1", name: "États-Unis", flag: "🇺🇸" },
  { id: "gb", code: "44", name: "Royaume-Uni", flag: "🇬🇧" },
  { id: "de", code: "49", name: "Allemagne", flag: "🇩🇪" },
  { id: "es", code: "34", name: "Espagne", flag: "🇪🇸" },
  { id: "it", code: "39", name: "Italie", flag: "🇮🇹" },
  { id: "nl", code: "31", name: "Pays-Bas", flag: "🇳🇱" },
  { id: "pt", code: "351", name: "Portugal", flag: "🇵🇹" },
  { id: "se", code: "46", name: "Suède", flag: "🇸🇪" },
  { id: "no", code: "47", name: "Norvège", flag: "🇳🇴" },
  { id: "dk", code: "45", name: "Danemark", flag: "🇩🇰" },
  { id: "fi", code: "358", name: "Finlande", flag: "🇫🇮" },
  { id: "at", code: "43", name: "Autriche", flag: "🇦🇹" },
  { id: "gr", code: "30", name: "Grèce", flag: "🇬🇷" },
  { id: "pl", code: "48", name: "Pologne", flag: "🇵🇱" },
  { id: "ma", code: "212", name: "Maroc", flag: "🇲🇦" },
  { id: "tn", code: "216", name: "Tunisie", flag: "🇹🇳" },
  { id: "ly", code: "218", name: "Libye", flag: "🇱🇾" },
  { id: "eg", code: "20", name: "Égypte", flag: "🇪🇬" },
  { id: "mr", code: "222", name: "Mauritanie", flag: "🇲🇷" },
  { id: "sn", code: "221", name: "Sénégal", flag: "🇸🇳" },
  { id: "ci", code: "225", name: "Côte d'Ivoire", flag: "🇨🇮" },
  { id: "cm", code: "237", name: "Cameroun", flag: "🇨🇲" },
  { id: "cd", code: "243", name: "RD Congo", flag: "🇨🇩" },
  { id: "cg", code: "242", name: "Congo", flag: "🇨🇬" },
  { id: "ga", code: "241", name: "Gabon", flag: "🇬🇦" },
  { id: "ng", code: "234", name: "Nigéria", flag: "🇳🇬" },
  { id: "gh", code: "233", name: "Ghana", flag: "🇬🇭" },
  { id: "sa", code: "966", name: "Arabie Saoudite", flag: "🇸🇦" },
  { id: "ae", code: "971", name: "Émirats Arabes Unis", flag: "🇦🇪" },
  { id: "qa", code: "974", name: "Qatar", flag: "🇶🇦" },
  { id: "kw", code: "965", name: "Koweït", flag: "🇰🇼" },
  { id: "bh", code: "973", name: "Bahreïn", flag: "🇧🇭" },
  { id: "om", code: "968", name: "Oman", flag: "🇴🇲" },
  { id: "jo", code: "962", name: "Jordanie", flag: "🇯🇴" },
  { id: "lb", code: "961", name: "Liban", flag: "🇱🇧" },
  { id: "sy", code: "963", name: "Syrie", flag: "🇸🇾" },
  { id: "iq", code: "964", name: "Irak", flag: "🇮🇶" },
  { id: "tr", code: "90", name: "Turquie", flag: "🇹🇷" },
  { id: "ru", code: "7", name: "Russie", flag: "🇷🇺" },
  { id: "cn", code: "86", name: "Chine", flag: "🇨🇳" },
  { id: "jp", code: "81", name: "Japon", flag: "🇯🇵" },
  { id: "in", code: "91", name: "Inde", flag: "🇮🇳" },
  { id: "br", code: "55", name: "Brésil", flag: "🇧🇷" },
  { id: "mx", code: "52", name: "Mexique", flag: "🇲🇽" },
  { id: "au", code: "61", name: "Australie", flag: "🇦🇺" },
  { id: "za", code: "27", name: "Afrique du Sud", flag: "🇿🇦" },
  { id: "af", code: "93", name: "Afghanistan", flag: "🇦🇫" },
  { id: "al", code: "355", name: "Albanie", flag: "🇦🇱" },
  { id: "ad", code: "376", name: "Andorre", flag: "🇦🇩" },
  { id: "ao", code: "244", name: "Angola", flag: "🇦🇴" },
  { id: "ag", code: "1268", name: "Antigua-et-Barbuda", flag: "🇦🇬" },
  { id: "ar", code: "54", name: "Argentine", flag: "🇦🇷" },
  { id: "am", code: "374", name: "Arménie", flag: "🇦🇲" },
  { id: "az", code: "994", name: "Azerbaïdjan", flag: "🇦🇿" },
  { id: "bs", code: "1242", name: "Bahamas", flag: "🇧🇸" },
  { id: "bd", code: "880", name: "Bangladesh", flag: "🇧🇩" },
  { id: "bb", code: "1246", name: "Barbade", flag: "🇧🇧" },
  { id: "by", code: "375", name: "Bélarus", flag: "🇧🇾" },
  { id: "bz", code: "501", name: "Belize", flag: "🇧🇿" },
  { id: "bj", code: "229", name: "Bénin", flag: "🇧🇯" },
  { id: "bt", code: "975", name: "Bhoutan", flag: "🇧🇹" },
  { id: "bo", code: "591", name: "Bolivie", flag: "🇧🇴" },
  { id: "ba", code: "387", name: "Bosnie-Herzégovine", flag: "🇧🇦" },
  { id: "bw", code: "267", name: "Botswana", flag: "🇧🇼" },
  { id: "bn", code: "673", name: "Brunéi", flag: "🇧🇳" },
  { id: "bg", code: "359", name: "Bulgarie", flag: "🇧🇬" },
  { id: "bf", code: "226", name: "Burkina Faso", flag: "🇧🇫" },
  { id: "bi", code: "257", name: "Burundi", flag: "🇧🇮" },
  { id: "cv", code: "238", name: "Cabo Verde", flag: "🇨🇻" },
  { id: "kh", code: "855", name: "Cambodge", flag: "🇰🇭" },
  { id: "cl", code: "56", name: "Chili", flag: "🇨🇱" },
  { id: "cy", code: "357", name: "Chypre", flag: "🇨🇾" },
  { id: "co", code: "57", name: "Colombie", flag: "🇨🇴" },
  { id: "km", code: "269", name: "Comores", flag: "🇰🇲" },
  { id: "cr", code: "506", name: "Costa Rica", flag: "🇨🇷" },
  { id: "hr", code: "385", name: "Croatie", flag: "🇭🇷" },
  { id: "cu", code: "53", name: "Cuba", flag: "🇨🇺" },
  { id: "dj", code: "253", name: "Djibouti", flag: "🇩🇯" },
  { id: "dm", code: "1767", name: "Dominique", flag: "🇩🇲" },
  { id: "ec", code: "593", name: "Équateur", flag: "🇪🇨" },
  { id: "er", code: "291", name: "Érythrée", flag: "🇪🇷" },
  { id: "sz", code: "268", name: "Eswatini", flag: "🇸🇿" },
  { id: "ee", code: "372", name: "Estonie", flag: "🇪🇪" },
  { id: "et", code: "251", name: "Éthiopie", flag: "🇪🇹" },
  { id: "fj", code: "679", name: "Fidji", flag: "🇫🇯" },
  { id: "gm", code: "220", name: "Gambie", flag: "🇬🇲" },
  { id: "ge", code: "995", name: "Géorgie", flag: "🇬🇪" },
  { id: "gd", code: "1473", name: "Grenade", flag: "🇬🇩" },
  { id: "gt", code: "502", name: "Guatemala", flag: "🇬🇹" },
  { id: "gn", code: "224", name: "Guinée", flag: "🇬🇳" },
  { id: "gw", code: "245", name: "Guinée-Bissau", flag: "🇬🇼" },
  { id: "gq", code: "240", name: "Guinée Équatoriale", flag: "🇬🇶" },
  { id: "gy", code: "592", name: "Guyana", flag: "🇬🇾" },
  { id: "ht", code: "509", name: "Haïti", flag: "🇭🇹" },
  { id: "hn", code: "504", name: "Honduras", flag: "🇭🇳" },
  { id: "hu", code: "36", name: "Hongrie", flag: "🇭🇺" },
  { id: "id", code: "62", name: "Indonésie", flag: "🇮🇩" },
  { id: "ir", code: "98", name: "Iran", flag: "🇮🇷" },
  { id: "ie", code: "353", name: "Irlande", flag: "🇮🇪" },
  { id: "is", code: "354", name: "Islande", flag: "🇮🇸" },
  { id: "jm", code: "1876", name: "Jamaïque", flag: "🇯🇲" },
  { id: "kz", code: "7", name: "Kazakhstan", flag: "🇰🇿" },
  { id: "ke", code: "254", name: "Kenya", flag: "🇰🇪" },
  { id: "kg", code: "996", name: "Kirghizistan", flag: "🇰🇬" },
  { id: "ki", code: "686", name: "Kiribati", flag: "🇰🇮" },
  { id: "la", code: "856", name: "Laos", flag: "🇱🇦" },
  { id: "ls", code: "266", name: "Lesotho", flag: "🇱🇸" },
  { id: "lv", code: "371", name: "Lettonie", flag: "🇱🇻" },
  { id: "lr", code: "231", name: "Libéria", flag: "🇱🇷" },
  { id: "li", code: "423", name: "Liechtenstein", flag: "🇱🇮" },
  { id: "lt", code: "370", name: "Lituanie", flag: "🇱🇹" },
  { id: "mk", code: "389", name: "Macédoine du Nord", flag: "🇲🇰" },
  { id: "mg", code: "261", name: "Madagascar", flag: "🇲🇬" },
  { id: "my", code: "60", name: "Malaisie", flag: "🇲🇾" },
  { id: "mw", code: "265", name: "Malawi", flag: "🇲🇼" },
  { id: "mv", code: "960", name: "Maldives", flag: "🇲🇻" },
  { id: "ml", code: "223", name: "Mali", flag: "🇲🇱" },
  { id: "mt", code: "356", name: "Malte", flag: "🇲🇹" },
  { id: "mh", code: "692", name: "Îles Marshall", flag: "🇲🇭" },
  { id: "mu", code: "230", name: "Maurice", flag: "🇲🇺" },
  { id: "fm", code: "691", name: "Micronésie", flag: "🇫🇲" },
  { id: "md", code: "373", name: "Moldavie", flag: "🇲🇩" },
  { id: "mc", code: "377", name: "Monaco", flag: "🇲🇨" },
  { id: "mn", code: "976", name: "Mongolie", flag: "🇲🇳" },
  { id: "me", code: "382", name: "Monténégro", flag: "🇲🇪" },
  { id: "mz", code: "258", name: "Mozambique", flag: "🇲🇿" },
  { id: "mm", code: "95", name: "Myanmar", flag: "🇲🇲" },
  { id: "na", code: "264", name: "Namibie", flag: "🇳🇦" },
  { id: "nr", code: "674", name: "Nauru", flag: "🇳🇷" },
  { id: "np", code: "977", name: "Népal", flag: "🇳🇵" },
  { id: "ni", code: "505", name: "Nicaragua", flag: "🇳🇮" },
  { id: "ne", code: "227", name: "Niger", flag: "🇳🇪" },
  { id: "nz", code: "64", name: "Nouvelle-Zélande", flag: "🇳🇿" },
  { id: "ug", code: "256", name: "Ouganda", flag: "🇺🇬" },
  { id: "uz", code: "998", name: "Ouzbékistan", flag: "🇺🇿" },
  { id: "pk", code: "92", name: "Pakistan", flag: "🇵🇰" },
  { id: "ps", code: "970", name: "Palestine", flag: "🇵🇸" },
  { id: "pw", code: "680", name: "Palaos", flag: "🇵🇼" },
  { id: "pa", code: "507", name: "Panama", flag: "🇵🇦" },
  { id: "pg", code: "675", name: "Papouasie-Nouvelle-Guinée", flag: "🇵🇬" },
  { id: "py", code: "595", name: "Paraguay", flag: "🇵🇾" },
  { id: "pe", code: "51", name: "Pérou", flag: "🇵🇪" },
  { id: "ph", code: "63", name: "Philippines", flag: "🇵🇭" },
  { id: "cf", code: "236", name: "République Centrafricaine", flag: "🇨🇫" },
  { id: "do", code: "1809", name: "République Dominicaine", flag: "🇩🇴" },
  { id: "cz", code: "420", name: "République Tchèque", flag: "🇨🇿" },
  { id: "ro", code: "40", name: "Roumanie", flag: "🇷🇴" },
  { id: "rw", code: "250", name: "Rwanda", flag: "🇷🇼" },
  { id: "kn", code: "1869", name: "Saint-Christophe-et-Niévès", flag: "🇰🇳" },
  { id: "sm", code: "378", name: "Saint-Marin", flag: "🇸🇲" },
  {
    id: "vc",
    code: "1784",
    name: "Saint-Vincent-et-les-Grenadines",
    flag: "🇻🇨",
  },
  { id: "lc", code: "1758", name: "Sainte-Lucie", flag: "🇱🇨" },
  { id: "sb", code: "677", name: "Îles Salomon", flag: "🇸🇧" },
  { id: "sv", code: "503", name: "Salvador", flag: "🇸🇻" },
  { id: "ws", code: "685", name: "Samoa", flag: "🇼🇸" },
  { id: "st", code: "239", name: "Sao Tomé-et-Principe", flag: "🇸🇹" },
  { id: "rs", code: "381", name: "Serbie", flag: "🇷🇸" },
  { id: "sc", code: "248", name: "Seychelles", flag: "🇸🇨" },
  { id: "sl", code: "232", name: "Sierra Leone", flag: "🇸🇱" },
  { id: "sg", code: "65", name: "Singapour", flag: "🇸🇬" },
  { id: "sk", code: "421", name: "Slovaquie", flag: "🇸🇰" },
  { id: "si", code: "386", name: "Slovénie", flag: "🇸🇮" },
  { id: "so", code: "252", name: "Somalie", flag: "🇸🇴" },
  { id: "sd", code: "249", name: "Soudan", flag: "🇸🇩" },
  { id: "ss", code: "211", name: "Soudan du Sud", flag: "🇸🇸" },
  { id: "lk", code: "94", name: "Sri Lanka", flag: "🇱🇰" },
  { id: "sr", code: "597", name: "Suriname", flag: "🇸🇷" },
  { id: "tj", code: "992", name: "Tadjikistan", flag: "🇹🇯" },
  { id: "tz", code: "255", name: "Tanzanie", flag: "🇹🇿" },
  { id: "td", code: "235", name: "Tchad", flag: "🇹🇩" },
  { id: "th", code: "66", name: "Thaïlande", flag: "🇹🇭" },
  { id: "tl", code: "670", name: "Timor Oriental", flag: "🇹🇱" },
  { id: "tg", code: "228", name: "Togo", flag: "🇹🇬" },
  { id: "to", code: "676", name: "Tonga", flag: "🇹🇴" },
  { id: "tt", code: "1868", name: "Trinité-et-Tobago", flag: "🇹🇹" },
  { id: "tm", code: "993", name: "Turkménistan", flag: "🇹🇲" },
  { id: "tv", code: "688", name: "Tuvalu", flag: "🇹🇻" },
  { id: "ua", code: "380", name: "Ukraine", flag: "🇺🇦" },
  { id: "uy", code: "598", name: "Uruguay", flag: "🇺🇾" },
  { id: "vu", code: "678", name: "Vanuatu", flag: "🇻🇺" },
  { id: "ve", code: "58", name: "Venezuela", flag: "🇻🇪" },
  { id: "vn", code: "84", name: "Viêt Nam", flag: "🇻🇳" },
  { id: "ye", code: "967", name: "Yémen", flag: "🇾🇪" },
  { id: "zm", code: "260", name: "Zambie", flag: "🇿🇲" },
  { id: "zw", code: "263", name: "Zimbabwe", flag: "🇿🇼" },
] as const;

export const LOCATION_TO_PHONE_CODE: Record<string, string> = {
  algerie: "213",
  france: "33",
  belgique: "32",
  suisse: "41",
  luxembourg: "352",
  canada: "1",
  "etats-unis": "1",
  "royaume-uni": "44",
  allemagne: "49",
  espagne: "34",
  italie: "39",
  "pays-bas": "31",
  portugal: "351",
  suede: "46",
  norvege: "47",
  danemark: "45",
  finlande: "358",
  autriche: "43",
  grece: "30",
  pologne: "48",
  maroc: "212",
  tunisie: "216",
  libye: "218",
  egypte: "20",
  mauritanie: "222",
  senegal: "221",
  "cote-divoire": "225",
  cameroun: "237",
  "republique-democratique-du-congo": "243",
  congo: "242",
  gabon: "241",
  nigeria: "234",
  ghana: "233",
  "arabie-saoudite": "966",
  "emirats-arabes-unis": "971",
  qatar: "974",
  koweit: "965",
  bahrein: "973",
  oman: "968",
  jordanie: "962",
  liban: "961",
  syrie: "963",
  irak: "964",
  turquie: "90",
  russie: "7",
  chine: "86",
  japon: "81",
  inde: "91",
  bresil: "55",
  mexique: "52",
  australie: "61",
  "afrique-du-sud": "27",
  afghanistan: "93",
  albanie: "355",
  andorre: "376",
  angola: "244",
  "antigua-et-barbuda": "1268",
  argentine: "54",
  armenie: "374",
  azerbaidjan: "994",
  bahamas: "1242",
  bangladesh: "880",
  barbade: "1246",
  belarus: "375",
  belize: "501",
  benin: "229",
  bhoutan: "975",
  bolivie: "591",
  "bosnie-herzegovine": "387",
  botswana: "267",
  brunei: "673",
  bulgarie: "359",
  "burkina-faso": "226",
  burundi: "257",
  "cabo-verde": "238",
  cambodge: "855",
  chili: "56",
  chypre: "357",
  colombie: "57",
  comores: "269",
  "costa-rica": "506",
  croatie: "385",
  cuba: "53",
  djibouti: "253",
  dominique: "1767",
  equateur: "593",
  erythree: "291",
  eswatini: "268",
  estonie: "372",
  ethiopie: "251",
  fidji: "679",
  gambie: "220",
  georgie: "995",
  grenade: "1473",
  guatemala: "502",
  guinee: "224",
  "guinee-bissau": "245",
  "guinee-equatoriale": "240",
  guyana: "592",
  haiti: "509",
  honduras: "504",
  hongrie: "36",
  indonesie: "62",
  iran: "98",
  irlande: "353",
  islande: "354",
  jamaique: "1876",
  kazakhstan: "7",
  kenya: "254",
  kirghizistan: "996",
  kiribati: "686",
  laos: "856",
  lesotho: "266",
  lettonie: "371",
  liberia: "231",
  liechtenstein: "423",
  lituanie: "370",
  "macedoine-du-nord": "389",
  madagascar: "261",
  malaisie: "60",
  malawi: "265",
  maldives: "960",
  mali: "223",
  malte: "356",
  marshall: "692",
  maurice: "230",
  micronesie: "691",
  moldavie: "373",
  monaco: "377",
  mongolie: "976",
  montenegro: "382",
  mozambique: "258",
  myanmar: "95",
  namibie: "264",
  nauru: "674",
  nepal: "977",
  nicaragua: "505",
  niger: "227",
  "nouvelle-zelande": "64",
  ouganda: "256",
  ouzbekistan: "998",
  pakistan: "92",
  palestine: "970",
  palaos: "680",
  panama: "507",
  "papouasie-nouvelle-guinee": "675",
  paraguay: "595",
  perou: "51",
  philippines: "63",
  "republique-centrafricaine": "236",
  "republique-dominicaine": "1809",
  "republique-tcheque": "420",
  roumanie: "40",
  rwanda: "250",
  "saint-christophe-et-nieves": "1869",
  "saint-marin": "378",
  "saint-vincent-et-grenadines": "1784",
  "sainte-lucie": "1758",
  salomon: "677",
  salvador: "503",
  samoa: "685",
  "sao-tome-et-principe": "239",
  serbie: "381",
  seychelles: "248",
  "sierra-leone": "232",
  singapour: "65",
  slovaquie: "421",
  slovenie: "386",
  somalie: "252",
  soudan: "249",
  "soudan-du-sud": "211",
  "sri-lanka": "94",
  suriname: "597",
  tadjikistan: "992",
  tanzanie: "255",
  tchad: "235",
  thailande: "66",
  "timor-oriental": "670",
  togo: "228",
  tonga: "676",
  "trinite-et-tobago": "1868",
  turkmenistan: "993",
  tuvalu: "688",
  ukraine: "380",
  uruguay: "598",
  vanuatu: "678",
  venezuela: "58",
  vietnam: "84",
  yemen: "967",
  zambie: "260",
  zimbabwe: "263",
};

export const LOCATION = [
  { value: "algerie", label: "Algérie" },
  { value: "afghanistan", label: "Afghanistan" },
  { value: "afrique-du-sud", label: "Afrique du Sud" },
  { value: "albanie", label: "Albanie" },
  { value: "allemagne", label: "Allemagne" },
  { value: "andorre", label: "Andorre" },
  { value: "angola", label: "Angola" },
  { value: "antigua-et-barbuda", label: "Antigua-et-Barbuda" },
  { value: "arabie-saoudite", label: "Arabie Saoudite" },
  { value: "argentine", label: "Argentine" },
  { value: "armenie", label: "Arménie" },
  { value: "australie", label: "Australie" },
  { value: "autriche", label: "Autriche" },
  { value: "azerbaidjan", label: "Azerbaïdjan" },
  { value: "bahamas", label: "Bahamas" },
  { value: "bahrein", label: "Bahreïn" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "barbade", label: "Barbade" },
  { value: "belarus", label: "Bélarus" },
  { value: "belgique", label: "Belgique" },
  { value: "belize", label: "Belize" },
  { value: "benin", label: "Bénin" },
  { value: "bhoutan", label: "Bhoutan" },
  { value: "bolivie", label: "Bolivie" },
  { value: "bosnie-herzegovine", label: "Bosnie-Herzégovine" },
  { value: "botswana", label: "Botswana" },
  { value: "bresil", label: "Brésil" },
  { value: "brunei", label: "Brunéi" },
  { value: "bulgarie", label: "Bulgarie" },
  { value: "burkina-faso", label: "Burkina Faso" },
  { value: "burundi", label: "Burundi" },
  { value: "cabo-verde", label: "Cabo Verde" },
  { value: "cambodge", label: "Cambodge" },
  { value: "cameroun", label: "Cameroun" },
  { value: "canada", label: "Canada" },
  { value: "chili", label: "Chili" },
  { value: "chine", label: "Chine" },
  { value: "chypre", label: "Chypre" },
  { value: "colombie", label: "Colombie" },
  { value: "comores", label: "Comores" },
  { value: "congo", label: "Congo" },
  { value: "costa-rica", label: "Costa Rica" },
  { value: "cote-divoire", label: "Côte d'Ivoire" },
  { value: "croatie", label: "Croatie" },
  { value: "cuba", label: "Cuba" },
  { value: "danemark", label: "Danemark" },
  { value: "djibouti", label: "Djibouti" },
  { value: "dominique", label: "Dominique" },
  { value: "egypte", label: "Égypte" },
  { value: "emirats-arabes-unis", label: "Émirats Arabes Unis" },
  { value: "equateur", label: "Équateur" },
  { value: "erythree", label: "Érythrée" },
  { value: "espagne", label: "Espagne" },
  { value: "eswatini", label: "Eswatini" },
  { value: "estonie", label: "Estonie" },
  { value: "etats-unis", label: "États-Unis" },
  { value: "ethiopie", label: "Éthiopie" },
  { value: "fidji", label: "Fidji" },
  { value: "finlande", label: "Finlande" },
  { value: "france", label: "France" },
  { value: "gabon", label: "Gabon" },
  { value: "gambie", label: "Gambie" },
  { value: "georgie", label: "Géorgie" },
  { value: "ghana", label: "Ghana" },
  { value: "grece", label: "Grèce" },
  { value: "grenade", label: "Grenade" },
  { value: "guatemala", label: "Guatemala" },
  { value: "guinee", label: "Guinée" },
  { value: "guinee-bissau", label: "Guinée-Bissau" },
  { value: "guinee-equatoriale", label: "Guinée Équatoriale" },
  { value: "guyana", label: "Guyana" },
  { value: "haiti", label: "Haïti" },
  { value: "honduras", label: "Honduras" },
  { value: "hongrie", label: "Hongrie" },
  { value: "inde", label: "Inde" },
  { value: "indonesie", label: "Indonésie" },
  { value: "irak", label: "Irak" },
  { value: "iran", label: "Iran" },
  { value: "irlande", label: "Irlande" },
  { value: "islande", label: "Islande" },
  { value: "italie", label: "Italie" },
  { value: "jamaique", label: "Jamaïque" },
  { value: "japon", label: "Japon" },
  { value: "jordanie", label: "Jordanie" },
  { value: "kazakhstan", label: "Kazakhstan" },
  { value: "kenya", label: "Kenya" },
  { value: "kirghizistan", label: "Kirghizistan" },
  { value: "kiribati", label: "Kiribati" },
  { value: "koweit", label: "Koweït" },
  { value: "laos", label: "Laos" },
  { value: "lesotho", label: "Lesotho" },
  { value: "lettonie", label: "Lettonie" },
  { value: "liban", label: "Liban" },
  { value: "liberia", label: "Libéria" },
  { value: "libye", label: "Libye" },
  { value: "liechtenstein", label: "Liechtenstein" },
  { value: "lituanie", label: "Lituanie" },
  { value: "luxembourg", label: "Luxembourg" },
  { value: "macedoine-du-nord", label: "Macédoine du Nord" },
  { value: "madagascar", label: "Madagascar" },
  { value: "malaisie", label: "Malaisie" },
  { value: "malawi", label: "Malawi" },
  { value: "maldives", label: "Maldives" },
  { value: "mali", label: "Mali" },
  { value: "malte", label: "Malte" },
  { value: "maroc", label: "Maroc" },
  { value: "marshall", label: "Îles Marshall" },
  { value: "maurice", label: "Maurice" },
  { value: "mauritanie", label: "Mauritanie" },
  { value: "mexique", label: "Mexique" },
  { value: "micronesie", label: "Micronésie" },
  { value: "moldavie", label: "Moldavie" },
  { value: "monaco", label: "Monaco" },
  { value: "mongolie", label: "Mongolie" },
  { value: "montenegro", label: "Monténégro" },
  { value: "mozambique", label: "Mozambique" },
  { value: "myanmar", label: "Myanmar" },
  { value: "namibie", label: "Namibie" },
  { value: "nauru", label: "Nauru" },
  { value: "nepal", label: "Népal" },
  { value: "nicaragua", label: "Nicaragua" },
  { value: "niger", label: "Niger" },
  { value: "nigeria", label: "Nigéria" },
  { value: "norvege", label: "Norvège" },
  { value: "nouvelle-zelande", label: "Nouvelle-Zélande" },
  { value: "oman", label: "Oman" },
  { value: "ouganda", label: "Ouganda" },
  { value: "ouzbekistan", label: "Ouzbékistan" },
  { value: "pakistan", label: "Pakistan" },
  { value: "palestine", label: "Palestine" },
  { value: "palaos", label: "Palaos" },
  { value: "panama", label: "Panama" },
  { value: "papouasie-nouvelle-guinee", label: "Papouasie-Nouvelle-Guinée" },
  { value: "paraguay", label: "Paraguay" },
  { value: "pays-bas", label: "Pays-Bas" },
  { value: "perou", label: "Pérou" },
  { value: "philippines", label: "Philippines" },
  { value: "pologne", label: "Pologne" },
  { value: "portugal", label: "Portugal" },
  { value: "qatar", label: "Qatar" },
  { value: "republique-centrafricaine", label: "République Centrafricaine" },
  {
    value: "republique-democratique-du-congo",
    label: "République Démocratique du Congo",
  },
  { value: "republique-dominicaine", label: "République Dominicaine" },
  { value: "republique-tcheque", label: "République Tchèque" },
  { value: "roumanie", label: "Roumanie" },
  { value: "royaume-uni", label: "Royaume-Uni" },
  { value: "russie", label: "Russie" },
  { value: "rwanda", label: "Rwanda" },
  { value: "saint-christophe-et-nieves", label: "Saint-Christophe-et-Niévès" },
  { value: "saint-marin", label: "Saint-Marin" },
  {
    value: "saint-vincent-et-grenadines",
    label: "Saint-Vincent-et-les-Grenadines",
  },
  { value: "sainte-lucie", label: "Sainte-Lucie" },
  { value: "salomon", label: "Îles Salomon" },
  { value: "salvador", label: "Salvador" },
  { value: "samoa", label: "Samoa" },
  { value: "sao-tome-et-principe", label: "Sao Tomé-et-Principe" },
  { value: "senegal", label: "Sénégal" },
  { value: "serbie", label: "Serbie" },
  { value: "seychelles", label: "Seychelles" },
  { value: "sierra-leone", label: "Sierra Leone" },
  { value: "singapour", label: "Singapour" },
  { value: "slovaquie", label: "Slovaquie" },
  { value: "slovenie", label: "Slovénie" },
  { value: "somalie", label: "Somalie" },
  { value: "soudan", label: "Soudan" },
  { value: "soudan-du-sud", label: "Soudan du Sud" },
  { value: "sri-lanka", label: "Sri Lanka" },
  { value: "suede", label: "Suède" },
  { value: "suisse", label: "Suisse" },
  { value: "suriname", label: "Suriname" },
  { value: "syrie", label: "Syrie" },
  { value: "tadjikistan", label: "Tadjikistan" },
  { value: "tanzanie", label: "Tanzanie" },
  { value: "tchad", label: "Tchad" },
  { value: "thailande", label: "Thaïlande" },
  { value: "timor-oriental", label: "Timor Oriental" },
  { value: "togo", label: "Togo" },
  { value: "tonga", label: "Tonga" },
  { value: "trinite-et-tobago", label: "Trinité-et-Tobago" },
  { value: "tunisie", label: "Tunisie" },
  { value: "turkmenistan", label: "Turkménistan" },
  { value: "turquie", label: "Turquie" },
  { value: "tuvalu", label: "Tuvalu" },
  { value: "ukraine", label: "Ukraine" },
  { value: "uruguay", label: "Uruguay" },
  { value: "vanuatu", label: "Vanuatu" },
  { value: "venezuela", label: "Venezuela" },
  { value: "vietnam", label: "Viêt Nam" },
  { value: "yemen", label: "Yémen" },
  { value: "zambie", label: "Zambie" },
  { value: "zimbabwe", label: "Zimbabwe" },
];

export const LANGUES = [
  "Arabe",
  "Français",
  "Anglais",
  "Tamazight",
  "Espagnol",
];

export const LANGUES_TRADUCTEUR = [
  "Arabe",
  "Français",
  "Anglais",
  "Tamazight",
  "Espagnol",
  "Allemand",
  "Russe",
  "Chinois",
  "Italien",
  "Turc",
];

export const GENRES = [
  { value: "homme", label: "M." },
  { value: "femme", label: "Mme" },
];
