export const REGIONS_FRANCE = [
  "Île-de-France",
  "Auvergne-Rhône-Alpes",
  "Provence-Alpes-Côte d'Azur",
  "Hauts-de-France",
  "Grand Est",
  "Occitanie",
  "Nouvelle-Aquitaine",
  "Bourgogne-Franche-Comté",
  "Normandie",
  "Centre-Val de Loire",
  "Pays de la Loire",
  "Bretagne",
  "Corse",
];

export const VILLES_PAR_REGION: Record<string, string[]> = {
  "Île-de-France": [
    "Paris",
    "Nanterre",
    "Saint-Denis",
    "Aubervilliers",
    "Montreuil",
    "Argenteuil",
    "Créteil",
    "Aulnay-sous-Bois",
    "Sarcelles",
    "Bobigny",
    "Évry-Courcouronnes",
    "Mantes-la-Jolie",
    "Trappes",
    "Boulogne-Billancourt",
    "Versailles",
    "Gennevilliers",
    "La Courneuve",
    "Clichy-sous-Bois",
    "Saint-Ouen-sur-Seine",
    "Vitry-sur-Seine",
  ],
  "Auvergne-Rhône-Alpes": [
    "Lyon",
    "Villeurbanne",
    "Vénissieux",
    "Vaulx-en-Velin",
    "Saint-Étienne",
    "Grenoble",
    "Annemasse",
    "Clermont-Ferrand",
    "Chambéry",
    "Valence",
    "Bourg-en-Bresse",
    "Roanne",
    "Annecy",
  ],
  "Provence-Alpes-Côte d'Azur": [
    "Marseille",
    "Nice",
    "Aix-en-Provence",
    "Toulon",
    "Avignon",
    "Cannes",
    "Arles",
    "Gap",
    "Fréjus",
    "Salon-de-Provence",
  ],
  "Hauts-de-France": [
    "Lille",
    "Roubaix",
    "Tourcoing",
    "Amiens",
    "Villeneuve-d'Ascq",
    "Wattrelos",
    "Douai",
    "Calais",
    "Dunkerque",
    "Valenciennes",
    "Béthune",
    "Lens",
  ],
  "Grand Est": [
    "Strasbourg",
    "Mulhouse",
    "Reims",
    "Metz",
    "Nancy",
    "Colmar",
    "Troyes",
    "Charleville-Mézières",
    "Épinal",
    "Haguenau",
  ],
  Occitanie: [
    "Toulouse",
    "Montpellier",
    "Nîmes",
    "Perpignan",
    "Béziers",
    "Narbonne",
    "Sète",
    "Carcassonne",
    "Albi",
  ],
  "Nouvelle-Aquitaine": [
    "Bordeaux",
    "Limoges",
    "Pau",
    "Bayonne",
    "Poitiers",
    "La Rochelle",
    "Mérignac",
    "Pessac",
    "Agen",
  ],
  "Bourgogne-Franche-Comté": [
    "Dijon",
    "Besançon",
    "Belfort",
    "Chalon-sur-Saône",
    "Montbéliard",
    "Nevers",
    "Auxerre",
    "Mâcon",
  ],
  Normandie: [
    "Rouen",
    "Le Havre",
    "Caen",
    "Cherbourg-en-Cotentin",
    "Évreux",
    "Dieppe",
    "Alençon",
  ],
  "Centre-Val de Loire": [
    "Tours",
    "Orléans",
    "Bourges",
    "Blois",
    "Châteauroux",
    "Chartres",
    "Dreux",
  ],
  "Pays de la Loire": [
    "Nantes",
    "Angers",
    "Le Mans",
    "Saint-Nazaire",
    "Cholet",
    "La Roche-sur-Yon",
  ],
  Bretagne: [
    "Rennes",
    "Brest",
    "Quimper",
    "Lorient",
    "Vannes",
    "Saint-Malo",
    "Saint-Brieuc",
  ],
  Corse: ["Ajaccio", "Bastia", "Porto-Vecchio"],
};
